<a href="https://colab.research.google.com/github/JavlonbekMirgaziev/data_science/blob/main/Arifmetik_ammalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data = np.arange(6).reshape(2,3)
data1 = np.arange(6,12).reshape(2,3)

In [ ]:
data*data1 # kopaytirish usuli

array([[ 0,  7, 16],
       [27, 40, 55]])

In [ ]:
data/data1

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [ ]:
data**data1

array([[       0,        1,      256],
       [   19683,  1048576, 48828125]])

In [ ]:
data + data1

array([[ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
data - data1

array([[-6, -6, -6],
       [-6, -6, -6]])

In [ ]:
data **3

array([[  0,   1,   8],
       [ 27,  64, 125]])