<a href="https://colab.research.google.com/github/JavlonbekMirgaziev/data_science/blob/main/birinchi_nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data1 = [234,235,234,457,256,] #list
arr1 = np.array(data1) #array1

In [ ]:
data1


[234, 235, 234, 457, 256]

In [ ]:
arr1

array([234, 235, 234, 457, 256])

In [ ]:
data2 = (2525,5235,25235,235235,) #tuple
arr2 = np.array(data2)

In [ ]:
data2

(2525, 5235, 25235, 235235)

In [ ]:
arr2

array([  2525,   5235,  25235, 235235])

massiv olchamini aniqlash

In [ ]:
arr1.ndim # array1 ning olchami. Bu  ".ndim" orqali aniqlanadi

1

Ikki va unda kotta massivlar


In [ ]:
data3 = [[1,2,3,4],[5,6,7,8]]
arr3 = np.array(data3)

In [ ]:
arr3.ndim # buning olchami 2 olchamni

2

In [ ]:
data4 = [[[[23,34,45,64]]]],[[[[34,34,657,343]]]]
arr4 = np.array(data4)

In [ ]:
arr4.ndim

4

shape , size metodlari

shape metodi massivlarni qatori va utunini korsatadi

In [ ]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr3.shape # shape- qator va stunlarni kortasatadi

(2, 4)

In [ ]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr3.size # elementlar sonini ko'rsatadi

8

N - o'lchamli massivlarni yaratishni boshqa  usullar

In [8]:
import numpy as np


In [9]:
arr4 = np.zeros(shape=(4,8))

In [10]:
arr4

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
arr5 = np.ones(shape=(5,6))
arr5

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
arr6 = np.arange(0,500,5)
arr6

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255,
       260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320,
       325, 330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385,
       390, 395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450,
       455, 460, 465, 470, 475, 480, 485, 490, 495])

In [21]:
arr7 = np.arange(1,100,2)
arr7

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])