<a href="https://colab.research.google.com/github/JavlonbekMirgaziev/data_science/blob/main/boolean_index4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [11]:
names = np.array(['Islom', 'Olim', 'Xusan', 'Xasan', 'Murod', 'Toxir', 'Sodiq'])
names

array(['Islom', 'Olim', 'Xusan', 'Xasan', 'Murod', 'Toxir', 'Sodiq'],
      dtype='<U5')

In [14]:
data = np.random.randn(7,4)
data

array([[-1.61760829,  0.06881997,  0.44333363, -0.57430938],
       [ 0.41764176, -0.14229615, -0.39681156, -0.15561894],
       [-0.92473587,  0.37201149, -0.46349732,  1.15867169],
       [-0.06594435,  0.10685651,  0.92917359,  0.11400671],
       [ 1.43750939,  0.09692198, -0.61333816, -0.55917059],
       [ 0.32717833, -1.12354841,  0.11116197,  1.71651623],
       [-1.7879935 ,  1.04113217,  0.98536422,  0.4806342 ]])

In [15]:
names == 'Xusan'

array([False, False,  True, False, False, False, False])

In [16]:
data [names == 'Xusan']

array([[-0.92473587,  0.37201149, -0.46349732,  1.15867169]])

In [17]:
data [names == 'Toxir']

array([[ 0.32717833, -1.12354841,  0.11116197,  1.71651623]])

In [18]:
data [names == 'Murod', 2:]

array([[-0.61333816, -0.55917059]])

In [19]:
data [names == 'Sodiq', 1]

array([1.04113217])

In [20]:
data[names != 'Xasan']

array([[-1.61760829,  0.06881997,  0.44333363, -0.57430938],
       [ 0.41764176, -0.14229615, -0.39681156, -0.15561894],
       [-0.92473587,  0.37201149, -0.46349732,  1.15867169],
       [ 1.43750939,  0.09692198, -0.61333816, -0.55917059],
       [ 0.32717833, -1.12354841,  0.11116197,  1.71651623],
       [-1.7879935 ,  1.04113217,  0.98536422,  0.4806342 ]])

In [21]:
data[names != 'Olim']

array([[-1.61760829,  0.06881997,  0.44333363, -0.57430938],
       [-0.92473587,  0.37201149, -0.46349732,  1.15867169],
       [-0.06594435,  0.10685651,  0.92917359,  0.11400671],
       [ 1.43750939,  0.09692198, -0.61333816, -0.55917059],
       [ 0.32717833, -1.12354841,  0.11116197,  1.71651623],
       [-1.7879935 ,  1.04113217,  0.98536422,  0.4806342 ]])

In [22]:
data[~(names == 'Xasan')]

array([[-1.61760829,  0.06881997,  0.44333363, -0.57430938],
       [ 0.41764176, -0.14229615, -0.39681156, -0.15561894],
       [-0.92473587,  0.37201149, -0.46349732,  1.15867169],
       [ 1.43750939,  0.09692198, -0.61333816, -0.55917059],
       [ 0.32717833, -1.12354841,  0.11116197,  1.71651623],
       [-1.7879935 ,  1.04113217,  0.98536422,  0.4806342 ]])

In [41]:
data[~(names == 'Toxir')]

array([[-1.61760829,  0.06881997,  0.44333363, -0.57430938],
       [ 0.41764176, -0.14229615, -0.39681156, -0.15561894],
       [-0.92473587,  0.37201149, -0.46349732,  1.15867169],
       [-0.06594435,  0.10685651,  0.92917359,  0.11400671],
       [ 1.43750939,  0.09692198, -0.61333816, -0.55917059],
       [-1.7879935 ,  1.04113217,  0.98536422,  0.4806342 ]])

In [42]:
print(names)
print(data)

['Islom' 'Olim' 'Xusan' 'Xasan' 'Murod' 'Toxir' 'Sodiq']
[[-1.61760829  0.06881997  0.44333363 -0.57430938]
 [ 0.41764176 -0.14229615 -0.39681156 -0.15561894]
 [-0.92473587  0.37201149 -0.46349732  1.15867169]
 [-0.06594435  0.10685651  0.92917359  0.11400671]
 [ 1.43750939  0.09692198 -0.61333816 -0.55917059]
 [ 0.32717833 -1.12354841  0.11116197  1.71651623]
 [-1.7879935   1.04113217  0.98536422  0.4806342 ]]


In [47]:
mask = (names == 'Xasan')| (names == 'Toxir')|(names == 'Murod')|(names == 'Olim')
mask

array([False,  True, False,  True,  True,  True, False])

In [48]:
data[mask]

array([[ 0.41764176, -0.14229615, -0.39681156, -0.15561894],
       [-0.06594435,  0.10685651,  0.92917359,  0.11400671],
       [ 1.43750939,  0.09692198, -0.61333816, -0.55917059],
       [ 0.32717833, -1.12354841,  0.11116197,  1.71651623]])

In [49]:
data

array([[-1.61760829,  0.06881997,  0.44333363, -0.57430938],
       [ 0.41764176, -0.14229615, -0.39681156, -0.15561894],
       [-0.92473587,  0.37201149, -0.46349732,  1.15867169],
       [-0.06594435,  0.10685651,  0.92917359,  0.11400671],
       [ 1.43750939,  0.09692198, -0.61333816, -0.55917059],
       [ 0.32717833, -1.12354841,  0.11116197,  1.71651623],
       [-1.7879935 ,  1.04113217,  0.98536422,  0.4806342 ]])

In [61]:
data[data >= 0] = 2

In [62]:
data

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])