<a href="https://colab.research.google.com/github/JavlonbekMirgaziev/data_science/blob/main/Indekslash_va_Kesish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [9]:
arr = np.arange(10,100,10)
slice_arr = arr [3:5].copy()
slice_arr [:] = 0
arr


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2d[1,0]

4

In [12]:
arr2d [0,0:]

array([1, 2, 3])

In [13]:
arr2d[1,2]

6

In [14]:
arr2d [1,1:3]

array([5, 6])

In [15]:
arr2d [:2,1:]

array([[2, 3],
       [5, 6]])

In [16]:
arr2d [:2,1:]

array([[2, 3],
       [5, 6]])

In [34]:
arr2d [2,2]

9

In [32]:
arr3d

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])