<a href="https://colab.research.google.com/github/JavlonbekMirgaziev/data_science/blob/main/Matematik_va_statistik_ammalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np


In [58]:
data = np.random.randn(7,4)
data

array([[-0.41681558,  0.75062364, -0.87929649, -1.05931636],
       [ 0.08920807,  0.70159139,  0.53363634, -0.18497346],
       [-0.57583369,  0.14546338, -0.43146014, -0.06338085],
       [ 2.13831438, -0.09234153,  1.18518744,  0.94251828],
       [ 0.10864867, -1.05818013,  0.69689091, -0.45703636],
       [-1.04362196, -0.38561118,  1.71920804,  0.99785778],
       [-0.86618965, -0.1449684 ,  0.91654823,  0.6431055 ]])

In [60]:
data.sum()

3.909776266401816

In [61]:
np.sum(data)

3.909776266401816

In [62]:
data.mean()

0.13963486665720773

In [64]:
mean = np.sum(data)/len(data)
mean

0.5585394666288309

In [67]:
data= np.mean(data, axis= 0)
data

0.13963486665720773

In [72]:
arrr = np.arange(101)
arrr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [74]:
arrr.cumsum()

array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485,
       1540, 1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145,
       2211, 2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926,
       3003, 3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828,
       3916, 4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851,
       4950, 5050])

In [75]:
k = np.sum(arrr)+len(arrr)

In [76]:
k

5151