<a href="https://colab.research.google.com/github/JavlonbekMirgaziev/data_science/blob/main/Transposing_and_Swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
A = np.arange(6).reshape(3,2)

In [7]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])

In [18]:
B = np.arange(100).reshape(10,10)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
B.T

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [20]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
A.swapaxes(1,0)

array([[0, 2, 4],
       [1, 3, 5]])

In [22]:
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
B.swapaxes(1,0)

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [24]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
np.dot(A,A.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [26]:
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
np.dot(B,B.T)

array([[  285,   735,  1185,  1635,  2085,  2535,  2985,  3435,  3885,
         4335],
       [  735,  2185,  3635,  5085,  6535,  7985,  9435, 10885, 12335,
        13785],
       [ 1185,  3635,  6085,  8535, 10985, 13435, 15885, 18335, 20785,
        23235],
       [ 1635,  5085,  8535, 11985, 15435, 18885, 22335, 25785, 29235,
        32685],
       [ 2085,  6535, 10985, 15435, 19885, 24335, 28785, 33235, 37685,
        42135],
       [ 2535,  7985, 13435, 18885, 24335, 29785, 35235, 40685, 46135,
        51585],
       [ 2985,  9435, 15885, 22335, 28785, 35235, 41685, 48135, 54585,
        61035],
       [ 3435, 10885, 18335, 25785, 33235, 40685, 48135, 55585, 63035,
        70485],
       [ 3885, 12335, 20785, 29235, 37685, 46135, 54585, 63035, 71485,
        79935],
       [ 4335, 13785, 23235, 32685, 42135, 51585, 61035, 70485, 79935,
        89385]])

In [35]:
C = np.arange(50).reshape(10,5)
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [44]:
C.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [45]:
np.dot(C,C.T)

array([[   30,    80,   130,   180,   230,   280,   330,   380,   430,
          480],
       [   80,   255,   430,   605,   780,   955,  1130,  1305,  1480,
         1655],
       [  130,   430,   730,  1030,  1330,  1630,  1930,  2230,  2530,
         2830],
       [  180,   605,  1030,  1455,  1880,  2305,  2730,  3155,  3580,
         4005],
       [  230,   780,  1330,  1880,  2430,  2980,  3530,  4080,  4630,
         5180],
       [  280,   955,  1630,  2305,  2980,  3655,  4330,  5005,  5680,
         6355],
       [  330,  1130,  1930,  2730,  3530,  4330,  5130,  5930,  6730,
         7530],
       [  380,  1305,  2230,  3155,  4080,  5005,  5930,  6855,  7780,
         8705],
       [  430,  1480,  2530,  3580,  4630,  5680,  6730,  7780,  8830,
         9880],
       [  480,  1655,  2830,  4005,  5180,  6355,  7530,  8705,  9880,
        11055]])