<a href="https://colab.research.google.com/github/JavlonbekMirgaziev/data_science/blob/main/Universal_funksiyalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np

In [51]:
xarr = np.arange(15)
yarr = np.arange(15,30)

In [52]:
print(xarr)
print(yarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [55]:
cond = np.array([True, False,  True,  False, True, False,  True,  False,True, False,  True,  False, True, False,  True,])

In [61]:
result = np.where(cond,xarr,yarr)
result

array([ 0, 16,  2, 18,  4, 20,  6, 22,  8, 24, 10, 26, 12, 28, 14])

In [64]:
rrr = np.random.randn(10,20)
rrr

array([[ 0.61822722, -1.30520931,  1.43467899,  0.9162178 , -0.91220017,
         1.1884093 , -1.1765496 , -0.14162514,  0.97210086, -2.05477091,
         1.13297952,  1.61545   , -1.04565712, -0.72558911, -0.26820128,
         1.29575279,  0.14983416, -0.67001734, -0.782055  , -0.95163288],
       [ 1.0982121 , -0.00977956, -0.01414168,  0.04924041,  0.35393712,
        -0.67829977,  0.13566643, -1.01843635,  1.23331401, -1.42702875,
         1.5584089 ,  0.72163553,  0.51609223,  0.5546618 ,  0.00448266,
         0.06066888, -0.28097317,  0.55530181,  0.63758739,  0.96557489],
       [-0.20620766,  0.69084679, -0.45405225,  0.20109626,  0.47655843,
        -0.38924042, -0.94043577,  1.66042197, -0.19238158,  1.33893123,
         1.09220212, -0.01891122,  0.91513203,  0.2340098 ,  0.98905317,
        -0.06431689,  2.31918127,  1.13474601,  0.31201166, -1.42588122],
       [ 1.80598107,  0.29163117,  0.21810584,  0.78702213, -1.72752423,
        -0.50922655, -0.10839326, -2.13508807,  

In [65]:
resultss = np.where(rrr > 0, 5, 10)
resultss


array([[ 5, 10,  5,  5, 10,  5, 10, 10,  5, 10,  5,  5, 10, 10, 10,  5,
         5, 10, 10, 10],
       [ 5, 10, 10,  5,  5, 10,  5, 10,  5, 10,  5,  5,  5,  5,  5,  5,
        10,  5,  5,  5],
       [10,  5, 10,  5,  5, 10, 10,  5, 10,  5,  5, 10,  5,  5,  5, 10,
         5,  5,  5, 10],
       [ 5,  5,  5,  5, 10, 10, 10, 10,  5, 10, 10,  5,  5,  5, 10,  5,
         5, 10, 10, 10],
       [ 5, 10,  5, 10,  5, 10,  5, 10,  5, 10,  5, 10, 10, 10,  5,  5,
         5,  5,  5, 10],
       [ 5, 10, 10,  5,  5,  5, 10, 10,  5,  5,  5,  5, 10,  5, 10,  5,
         5, 10,  5, 10],
       [ 5,  5, 10, 10, 10,  5,  5,  5, 10, 10, 10, 10, 10, 10, 10,  5,
         5,  5,  5, 10],
       [ 5, 10, 10,  5, 10, 10, 10, 10, 10, 10,  5, 10,  5,  5, 10,  5,
        10, 10, 10,  5],
       [10,  5, 10, 10,  5, 10, 10, 10, 10,  5,  5, 10, 10,  5, 10, 10,
         5,  5, 10, 10],
       [ 5,  5, 10, 10,  5, 10,  5, 10,  5,  5, 10,  5,  5,  5, 10, 10,
         5,  5,  5, 10]])