<a href="https://colab.research.google.com/github/JavlonbekMirgaziev/data_science/blob/main/Universal_funksiyalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

*sqrt, square, exp, log, modf, sign, isnan*

In [2]:
arr = np.arange(100)

In [3]:
np.sqrt(arr)# kvatrat ildizni hisobledi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386,
       8.36660027, 8.42614977, 8.48528137, 8.54400375, 8.60232

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
np.square(arr) # arrayni barcha qiymatlarini kvatratga oshiradi

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [8]:
np.exp(arr) #arrayni darajaga oshiradi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16,
       2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
       1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
       7.01673591e+20, 1.90734657e+21, 5.18470553e+21, 1.40934908e+22,
       3.83100800e+22, 1.04137594e+23, 2.83075330e+23, 7.69478527e+23,
      

In [10]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
       3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
       3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
       3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301,
       3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319,
       4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456,
       4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727,
       4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524,
       4.26267988, 4.27666612, 4.29045944, 4.30406509, 4.31748

In [15]:
arr1 = np.random.randn(7,4)
arr1

array([[ 1.49109767,  0.03839542, -0.40557625,  0.24254308],
       [-1.36199841, -0.33557354,  0.64709961, -0.40155776],
       [-0.05582892,  2.48494805, -1.05034567, -0.53591577],
       [-0.23098018,  0.29928237, -0.15025996, -0.07158683],
       [-2.03477761,  0.57963646,  0.7362279 ,  0.16750538],
       [ 2.31747383, -0.11937789,  2.87604985, -1.07752548],
       [-0.80486023,  1.04050764,  0.1283753 ,  1.0356296 ]])

In [16]:
qoldiq,buttun = np.modf(arr1)

In [20]:
print(qoldiq)
print(buttun)

[[ 0.49109767  0.03839542 -0.40557625  0.24254308]
 [-0.36199841 -0.33557354  0.64709961 -0.40155776]
 [-0.05582892  0.48494805 -0.05034567 -0.53591577]
 [-0.23098018  0.29928237 -0.15025996 -0.07158683]
 [-0.03477761  0.57963646  0.7362279   0.16750538]
 [ 0.31747383 -0.11937789  0.87604985 -0.07752548]
 [-0.80486023  0.04050764  0.1283753   0.0356296 ]]
[[ 1.  0. -0.  0.]
 [-1. -0.  0. -0.]
 [-0.  2. -1. -0.]
 [-0.  0. -0. -0.]
 [-2.  0.  0.  0.]
 [ 2. -0.  2. -1.]
 [-0.  1.  0.  1.]]


In [21]:
np.sign(arr1)

array([[ 1.,  1., -1.,  1.],
       [-1., -1.,  1., -1.],
       [-1.,  1., -1., -1.],
       [-1.,  1., -1., -1.],
       [-1.,  1.,  1.,  1.],
       [ 1., -1.,  1., -1.],
       [-1.,  1.,  1.,  1.]])

In [23]:
np.isnan(arr1)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
arr1[3] = np.nan

In [28]:
np.isnan(arr1)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
arr2 = np.random.randn(100)
arr3 = np.random.randn(100)

In [33]:
np.add(arr2,arr3) #qoshib beradi
#arr2+arr3 ikkovi bir xil natijani qaytaradi

array([-1.97613658,  1.44383147,  0.1258025 , -0.28934524,  0.39033284,
       -3.93331179, -1.72627147, -1.85038085, -0.883753  , -0.16501844,
        1.81189255,  0.16276444, -1.21112612,  0.06955688, -0.79474592,
       -0.90024936,  0.04215865, -0.71511603, -1.46139272, -1.14048947,
       -2.90012659,  1.25630012,  0.36474342, -0.83016899,  0.11448151,
       -0.38902015, -0.77400546,  0.05747735,  1.28181593,  3.16942891,
        0.620606  ,  0.13868311, -1.47970866,  1.15315487, -2.22962407,
       -1.77881335, -1.83311992,  1.87787479, -0.83126114, -1.33609629,
        1.05066698,  0.10738034, -2.49162537, -1.68016367,  2.0382758 ,
       -1.00488598, -2.15075997,  1.24180281,  0.04608092, -1.56480271,
        2.00346988,  0.76181025, -2.20370441,  1.08701772,  0.32576219,
        1.44665877, -1.30974992, -0.3090566 ,  1.23321217, -0.17809436,
       -1.62067909, -1.52833647, -0.02511392,  2.51485541, -2.03291307,
        0.15212323, -0.7353475 ,  1.5559285 , -0.63606791, -2.66

In [31]:
arr2

array([-1.65233146,  0.80247444,  0.47208934, -0.65276321, -0.30960599,
       -1.60964361, -1.14835513, -0.35889784,  0.19795341,  0.58851612,
        1.24457353,  0.37035665, -1.9272164 ,  1.46042441,  0.50527415,
       -0.09104681,  1.63986025, -0.33473829, -1.45819814,  1.01011042,
       -0.2011225 ,  0.82127393, -0.39832027,  0.13329279, -0.17424237,
       -0.23350939,  0.10684484, -0.08867695, -0.32651139,  1.86785646,
        0.43617746,  0.00868507, -0.48449959,  0.32531118, -2.26805371,
       -1.19069204, -1.81509912,  1.00851553, -0.55770872, -0.95036041,
        0.63546696, -0.98335542, -0.66917675, -0.63624235,  0.97008403,
       -0.89352945, -1.78194131,  1.79995895,  0.27892387,  0.31558532,
        1.5632579 ,  1.06903405, -0.23167361, -0.32082397,  0.51549007,
        0.60523591, -0.44642255,  0.20901471,  1.84995509,  0.91004966,
       -0.69731794, -1.53105044,  1.45551459,  1.47183932, -1.9149263 ,
        0.75907261,  0.28510775,  1.09930027,  0.20411348, -0.70

In [32]:
arr3

array([-0.32380513,  0.64135703, -0.34628684,  0.36341797,  0.69993884,
       -2.32366818, -0.57791634, -1.49148301, -1.08170641, -0.75353456,
        0.56731902, -0.20759221,  0.71609027, -1.39086753, -1.30002007,
       -0.80920255, -1.5977016 , -0.38037775, -0.00319458, -2.15059989,
       -2.69900409,  0.43502619,  0.76306369, -0.96346178,  0.28872388,
       -0.15551076, -0.8808503 ,  0.1461543 ,  1.60832732,  1.30157245,
        0.18442854,  0.12999804, -0.99520907,  0.82784369,  0.03842963,
       -0.5881213 , -0.0180208 ,  0.86935926, -0.27355242, -0.38573588,
        0.41520002,  1.09073576, -1.82244862, -1.04392132,  1.06819176,
       -0.11135653, -0.36881866, -0.55815614, -0.23284295, -1.88038803,
        0.44021198, -0.3072238 , -1.9720308 ,  1.40784169, -0.18972788,
        0.84142286, -0.86332737, -0.51807131, -0.61674292, -1.08814402,
       -0.92336115,  0.00271397, -1.48062851,  1.04301609, -0.11798677,
       -0.60694938, -1.02045525,  0.45662823, -0.8401814 , -1.95

In [35]:
np.multiply(arr2,arr3) #bu kopaytiradi sonlarni bir biriga

array([ 5.35033398e-01,  5.14672621e-01, -1.63478328e-01, -2.37225878e-01,
       -2.16705259e-01,  3.74027765e+00,  6.63653192e-01,  5.35290034e-01,
       -2.14127471e-01, -4.43467230e-01,  7.06070235e-01, -7.68831532e-02,
       -1.38006092e+00, -2.03125689e+00, -6.56866530e-01,  7.36753101e-02,
       -2.62000734e+00,  1.27326995e-01,  4.65832837e-03, -2.17234334e+00,
        5.42830437e-01,  3.57275671e-01, -3.03943738e-01, -1.28422509e-01,
       -5.03079332e-02,  3.63132233e-02, -9.41143066e-02, -1.29605181e-02,
       -5.25137188e-01,  2.43115051e+00,  8.04435701e-02,  1.12904234e-03,
        4.82178383e-01,  2.69306810e-01, -8.71604758e-02,  7.00271358e-01,
        3.27095436e-02,  8.76762319e-01,  1.52562569e-01,  3.66588109e-01,
        2.63845893e-01, -1.07258093e+00,  1.21954024e+00,  6.64186953e-01,
        1.03623578e+00,  9.95003397e-02,  6.57213203e-01, -1.00465814e+00,
       -6.49454578e-02, -5.93422848e-01,  6.88164854e-01, -3.28432709e-01,
        4.56867492e-01, -

In [36]:
np.maximum(arr2,arr3)

array([-0.32380513,  0.80247444,  0.47208934,  0.36341797,  0.69993884,
       -1.60964361, -0.57791634, -0.35889784,  0.19795341,  0.58851612,
        1.24457353,  0.37035665,  0.71609027,  1.46042441,  0.50527415,
       -0.09104681,  1.63986025, -0.33473829, -0.00319458,  1.01011042,
       -0.2011225 ,  0.82127393,  0.76306369,  0.13329279,  0.28872388,
       -0.15551076,  0.10684484,  0.1461543 ,  1.60832732,  1.86785646,
        0.43617746,  0.12999804, -0.48449959,  0.82784369,  0.03842963,
       -0.5881213 , -0.0180208 ,  1.00851553, -0.27355242, -0.38573588,
        0.63546696,  1.09073576, -0.66917675, -0.63624235,  1.06819176,
       -0.11135653, -0.36881866,  1.79995895,  0.27892387,  0.31558532,
        1.5632579 ,  1.06903405, -0.23167361,  1.40784169,  0.51549007,
        0.84142286, -0.44642255,  0.20901471,  1.84995509,  0.91004966,
       -0.69731794,  0.00271397,  1.45551459,  1.47183932, -0.11798677,
        0.75907261,  0.28510775,  1.09930027,  0.20411348, -0.70